//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NarrativeArc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NarrativeArc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Staging
        ///2	PlotProgression
        ///3	CognitiveTension
        ///%
        ///a	1
        ///abnormal*	3
        ///about	1
        ///above	1
        ///absolutely	2
        ///abt	1
        ///acknowledg*	3
        ///across	1
        ///actually	2	3
        ///adjust*	3
        ///admit	3
        ///admits	3
        ///admitted	3
        ///admitting	3
        ///affect	3
        ///affected	3
        ///affecting	3
        ///affects	3
        ///after	1
        ///afterthought*	3
        ///again	2
        ///against	1
        ///ahead	1
        ///aint	2
        ///ain&apos;t	2
        ///all	2
        ///almost	2
        ///along	1
        ///already	2
        ///also	2	3
        ///alternate	3
        ///alternative	3
        ///alternatively	2	3
        ///alternatives	3
        ///altho	2	3
        ///although	2	3
        ///altogether	2
        ///always	2
        ///am	2
        ///ambigu*	3
        ///amid	1
        ///ami [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AONwithDependencies {
            get {
                return ResourceManager.GetString("AONwithDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Staging
        ///2	PlotProgression
        ///3	CognitiveTension
        ///%
        ///a	1
        ///abnormal*	3
        ///about	1
        ///above	1
        ///absolutely	2
        ///abt	1
        ///acknowledg*	3
        ///across	1
        ///actually	2
        ///adjust*	3
        ///admit	3
        ///admits	3
        ///admitted	3
        ///admitting	3
        ///affect	3
        ///affected	3
        ///affecting	3
        ///affects	3
        ///after	1
        ///afterthought*	3
        ///again	2
        ///against	1
        ///ahead	1
        ///aint	2
        ///ain&apos;t	2
        ///all	2
        ///almost	2
        ///along	1
        ///already	2
        ///also	2
        ///alternate	3
        ///alternative	3
        ///alternatively	2
        ///alternatives	3
        ///altho	2
        ///although	2
        ///altogether	2
        ///always	2
        ///am	2
        ///ambigu*	3
        ///amid	1
        ///amidst	1
        ///amo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AONwithoutDependencies {
            get {
                return ResourceManager.GetString("AONwithoutDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
